version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    environment:
      APP_ENV: spec
      MID: 211134
      REDIS_URL: 127.0.0.1:6379
      RECOMMENDATION: home
      CACHE_EXPIRY: 10
      DESKTOP_BUCKET_ID: 3
      MOBILE_BUCKET_ID: 7
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

workflows:
  version: 2
  build-deploy:
    jobs:
      - lint
      - build


